[build]
  # The command to run before deploying
  command = "npm run build"
  # The directory that Netlify will serve after the build process finishes
  publish = "build"

# This rule makes sure all paths route back to your single-page React application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
